version: '2'
services:
    db_postgres:
        image: postgres:9.5.2
        ports:
         - "5432:5432"
        environment:
         - POSTGRES_PASSWORD=postgres
    db_mysql:
        image: mysql:5.7.12
        ports:
         - "3306:3306"
        environment:
         - MYSQL_ROOT_PASSWORD=mysql